{"name": "Отображается сообщение об ошибке после запроса без id", "status": "passed", "start": 1734079735878, "stop": 1734079735942, "uuid": "6fc6eb3e-12b2-4e8c-8c4e-9a7d33aa9307", "historyId": "7dd27198fcccd4dcf275c08d7c1560e3", "testCaseId": "7dd27198fcccd4dcf275c08d7c1560e3", "fullName": "tests.test_get_order_using_his_number.TestGetOrder#test_error_message_after_request_without_track_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_using_his_number"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "WIN-3SKQPE0FURM"}, {"name": "thread", "value": "10304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_using_his_number"}], "links": [{"type": "link", "url": "https://qa-scooter.praktikum-services.ru", "name": "https://qa-scooter.praktikum-services.ru"}]}